### PR TITLE
React -  Todo list basic functionality.

### PR DESCRIPTION
**Pull request by wandergithub**
### Added To-do list using React, following the [tutorial instructions](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/exercises/react_tutorial.md).
1. [Initialized the React app.](https://github.com/wandergithub/To-do-React/commit/97433ad27f6c9e887654afa5407525d62f3204f0)
2. [Delete boilerplate code and files](https://github.com/wandergithub/To-do-React/commit/295048f3607410f107b02127c1a82190bbbe5797)
3. [Create class based components.](https://github.com/wandergithub/To-do-React/commit/1f89fbe3102b836953babf08301a2595818ffb72)
4. [Add form functionality and event handlers](https://github.com/wandergithub/To-do-React/commit/a84a2bf29aa08e004936cfb7528c405181c393a9)
5. [Add style using inline style, CSS modules and CSS stylesheets.](https://github.com/wandergithub/To-do-React/commit/d480c3daa401e14867d25aaf356b192075fb1e61)

### CODE REVIEW

**Review by rbanos-mv — CHANGES_REQUESTED** [review]
@wandergithub 
Good job so far!

There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

almost-there

## Required changes
Check if the repo is professional according to the basic rules:
- [x] The README file is empty. Please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.

Check linter:
- [ ] The linters are not running at GitHub. Please be sure the linters are set up correctly for this repository.
- [ ] Please verify that the linters result is green. AKA: Linter should report NO errors.



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by wandergithub** [comment]
Thanks for the suggestions  @rbanos-mv. :raised_hands:
I'll fill out the README file and check the linters right away.

**Review by rbanos-mv — APPROVED** [review]
# Hi @wandergithub  👋🏽 

Your project is complete!  There is nothing else to say other than… it's time to merge it.
Congratulations! 🎉 

## To highlight 🎯
- No linter errors.✔️
- Good code design and implementation. ✔️
-  Everything works and looks good on the browser.✔️ 
- Good documentation. ✔️ 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question, so I can receive the notification.

**Comment by wandergithub** [comment]
Thanks :smiley: @rbanos-mv,  I'll proceed and close this PR.

**Pull request merged**
